source 'https://rubygems.org'

gem 'quickbooks-ruby'
gem 'quickbooks-ruby-base'
gem 'oauth-plugin'#, '~> 0.5.1'
gem 'oauth'
gem 'roxml'
#gem 'nokogiri'
gem 'edmunds_vin'
gem 'will_paginate', '~> 3.1.0'
gem 'delayed_job_active_record'
